### ISSUE TITLE
hbuilderx运行失败

### ISSUE THREAD

**Issue by huangying2001** [AmosHuKe/Watch-Test#4]
# 问题标题

问题描述: 
14:32:09.404 项目 'Watch-Test-master' 开始编译...
14:32:18.480 Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
14:32:18.483 ModuleBuildError: Module build failed (from ./node_modules/less-loader/dist/cjs.js):
14:32:18.483 Class constructor FileManager cannot be invoked without 'new'
14:32:18.486       in undefined (line undefined, column undefined)
14:32:18.486     at runLoaders (D:\Program Files\HBuilderX\plugins\uniapp-cli\node_modules\webpack\lib\NormalModule.js:301:20)
14:32:18.493     at D:\Program Files\HBuilderX\plugins\uniapp-cli\node_modules\loader-runner\lib\LoaderRunner.js:367:11
14:32:18.493     at D:\Program Files\HBuilderX\plugins\uniapp-cli\node_modules\loader-runner\lib\LoaderRunner.js:233:18
14:32:18.498     at context.callback (D:\Program Files\HBuilderX\plugins\uniapp-cli\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
14:32:18.498     at <anonymous>
14:32:18.508     at runMicrotasksCallback (internal/process/next_tick.js:121:5)
14:32:18.509     at _combinedTickCallback (internal/process/next_tick.js:131:7)
14:32:18.515     at process._tickCallback (internal/process/next_tick.js:180:9)
14:32:18.526  ERROR  Build failed with errors.
关联需求: 

## 复现步骤

1. 
2. 
3. 

## 错误信息或者截图

```text
 
```

**Comment by AmosHuKe** [comment]
可能是没有开启Less导致的，HbuilderX上选择工具–>安装插件–>搜索安装Less，重新启动试试。

**Comment by AmosHuKe** [comment]
这个Bug已经修复好了，重新克隆下项目，
HbuilderX上选择工具–>安装插件–>搜索安装Scss

**Comment by AmosHuKe** [comment]
这个Bug已经修复好了，重新克隆下项目，
HbuilderX上选择工具–>安装插件–>搜索安装Scss
