### ISSUE TITLE
json数据404了建议直接放项目下

### ISSUE THREAD

**Issue by bref0** [AmosHuKe/Watch-Test#5]
# 问题标题

问题描述: 

关联需求: 

## 复现步骤

1. 
2. 
3. 

## 错误信息或者截图

```text
 
```

**Comment by AmosHuKe** [comment]
感谢~ 已经改为本地 json-server 服务。
[README/本地数据服务](https://github.com/AmosHuKe/Watch-Test#%EF%B8%8F-%E6%9C%AC%E5%9C%B0%E6%95%B0%E6%8D%AE%E6%9C%8D%E5%8A%A1)
